version: "3"

services:
  mongodb:
    image: mongo
    container_name: my_database
    ports:
      - "27017:27107"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb
    links:
      - mongodb

  server-app:
    container_name: hotel-app-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - mongo-seed
    entrypoint: ["app-exe", "start"]
